version: "3.5"

networks:
  buildnet:
    name: buildnet
    external: true

volumes:
  skei_data:
    driver: local

services:
  skei:
    container_name: skei
    image: skei/skei:dev
    restart: always
    networks:
      - buildnet
    volumes:
      - skei_data:/data
    ports:
      - "222:22"
