version: "3.5"

networks:
  skeinet:
    name: skeinet
    external: false
    driver: bridge

volumes:
  skei_data:
    driver: local

services:
  traefik:
    container_name: traefik
    image: traefik:1.5.4
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - skeinet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json

  skei:
    container_name: skei
    image: skei/skei:dev
    restart: always
    networks:
      - skeinet
    volumes:
      - skei_data:/data
    ports:
      - "222:22"
    labels:
      - "traefik.docker.network=skeinet"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:skei.dev,www.skei.dev"
      - "traefik.basic.port=3000"
      - "traefik.basic.protocol=http"

  vanity:
    container_name: vanity
    image: skei/vanity:dev
    restart: always
    networks:
      - skeinet
    volumes:
      - ./vanity_repos:/repos
    command: -index code.skei.dev
    labels:
      - "traefik.docker.network=skeinet"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:code.skei.dev"
      - "traefik.basic.port=8080"
      - "traefik.basic.protocol=http"
