version: "3.5"

networks:
  buildnet:
    name: buildnet
    external: false
    driver: bridge

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    networks:
      - buildnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
    ports:
      - '80:80'
      - '443:443'
